language: java
sudo: false
jdk: openjdk8
install: true
before_script: sudo apt-get install openjfx
script: mvn test

notifications:
  email:
    recipients:
      - blackjneco@gmail.com
      - blackjneco@mailfence.com
    on_success: always # default: change
    on_failure: always # default